# Generated by Django 4.2 on 2025-12-17 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="小区名称")),
                ("address", models.CharField(max_length=200, verbose_name="小区地址")),
                (
                    "developer",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="开发商"
                    ),
                ),
                (
                    "property_company",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="物业公司"
                    ),
                ),
                (
                    "build_time",
                    models.DateField(blank=True, null=True, verbose_name="建成时间"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_communities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="小区管理员",
                    ),
                ),
            ],
            options={"verbose_name": "小区", "verbose_name_plural": "小区",},
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="楼栋名称")),
                ("unit_count", models.IntegerField(default=1, verbose_name="单元数")),
                ("floor_count", models.IntegerField(default=18, verbose_name="楼层数")),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.community",
                        verbose_name="所属小区",
                    ),
                ),
            ],
            options={"verbose_name": "楼栋", "verbose_name_plural": "楼栋",},
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.IntegerField(verbose_name="单元号")),
                ("floor", models.IntegerField(verbose_name="楼层")),
                ("room_number", models.CharField(max_length=10, verbose_name="房间号")),
                ("area", models.FloatField(verbose_name="房屋面积")),
                ("is_rented", models.BooleanField(default=False, verbose_name="是否出租")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.building",
                        verbose_name="所属楼栋",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="房屋业主",
                    ),
                ),
            ],
            options={
                "verbose_name": "房屋",
                "verbose_name_plural": "房屋",
                "unique_together": {("building", "unit", "floor", "room_number")},
            },
        ),
    ]
