# Generated by Django 4.2 on 2025-12-17 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepairOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="报修标题")),
                ("content", models.TextField(verbose_name="报修内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completion_note",
                    models.TextField(blank=True, null=True, verbose_name="完成备注"),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repair_handler",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.house",
                        verbose_name="报修房屋",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_reporter",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="报修人",
                    ),
                ),
            ],
            options={"verbose_name": "报修单", "verbose_name_plural": "报修单",},
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("property_fee", "物业费"),
                            ("water_fee", "水费"),
                            ("electric_fee", "电费"),
                            ("gas_fee", "燃气费"),
                            ("parking_fee", "停车费"),
                            ("other", "其他费用"),
                        ],
                        max_length=20,
                        verbose_name="缴费类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="缴费金额"
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="缴费时间"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="缴费方式"
                    ),
                ),
                (
                    "third_party_order_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="第三方订单号"
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.house",
                        verbose_name="缴费房屋",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="缴费人",
                    ),
                ),
            ],
            options={"verbose_name": "缴费记录", "verbose_name_plural": "缴费记录",},
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "publish_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                ("is_top", models.BooleanField(default=False, verbose_name="是否置顶")),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.community",
                        verbose_name="所属小区",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "小区公告",
                "verbose_name_plural": "小区公告",
                "ordering": ["-is_top", "-publish_time"],
            },
        ),
    ]
